src/objects/Answer__c.object
<CustomObject>
    <fields>
        <fullName>Question__c</fullName>
        <label>Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Answers</relationshipLabel>
        <relationshipName>Answers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Right__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Right</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Variant__c</fullName>
        <label>Variant</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Answer</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Answer #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Question__c.object
<CustomObject>
    <fields>
        <fullName>Level__c</fullName>
        <label>Level</label>
        <picklist>
            <picklistValues>
                <fullName>Junior</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Middle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Senior</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Statement__c</fullName>
        <label>Statement</label>
        <length>4096</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Theme__c</fullName>
        <label>Theme</label>
        <referenceTo>Theme__c</referenceTo>
        <relationshipLabel>Questions</relationshipLabel>
        <relationshipName>Questions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Question</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Question #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Subject__c.object
<CustomObject>
    <label>Subject</label>
    <nameField>
        <label>Subject Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subjects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Test__c.object
<CustomObject>
    <fields>
        <fullName>Subject__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subject</label>
        <referenceTo>Subject__c</referenceTo>
        <relationshipLabel>Tests</relationshipLabel>
        <relationshipName>Tests</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Test</label>
    <nameField>
        <label>Test Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Theme__c.object
<CustomObject>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <referenceTo>Subject__c</referenceTo>
        <relationshipName>Themes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Topic</label>
    <nameField>
        <label>Topic Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Topics</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/KACommonSubjectsControllerTest.cls
@isTest
private class KACommonSubjectsControllerTest {

	private static KACommonSubjectsController subjectsController;

	private static void init() {
		Subject__c testSubject = new Subject__c(Name = 'testSubject');
		insert testSubject;

		Test__c testTest = new Test__c(Duration__c = 120, Subject__c = testSubject.Id);
		insert testTest;

		Theme__c testTheme = new Theme__c(Name = 'testTheme', Subject__c = testSubject.Id);
		insert testTheme;

		TestTheme__c testTestTheme = new TestTheme__c(Theme__c = testTheme.Id, Test__c = testTest.Id, Questions_Captured__c = 2);
		insert testTestTheme;

		Question__c testQuestion = new Question__c(Theme__c = testTheme.Id, Statement__c = 'testStatement', Level__c = 'Junior');
		insert testQuestion;

		Answer__c testFirstAnswer = new Answer__c(Question__c = testQuestion.Id, Variant__c = 'testVariant', Right__c = true);
		Answer__c testSecondAnswer = new Answer__c(Question__c = testQuestion.Id, Variant__c = 'testVariant', Right__c = false);
		insert testFirstAnswer;
		insert testSecondAnswer;

		Question__c testQuestion2 = new Question__c(Theme__c = testTheme.Id, Statement__c = 'testStatement', Level__c = 'Junior');
		insert testQuestion2;

		Answer__c testFirstAnswer2 = new Answer__c(Question__c = testQuestion2.Id, Variant__c = 'testVariant', Right__c = true);
		Answer__c testSecondAnswer2 = new Answer__c(Question__c = testQuestion2.Id, Variant__c = 'testVariant', Right__c = true);
		insert testFirstAnswer2;
		insert testSecondAnswer2;

		DropBox__c dropToken = new DropBox__c(Name = 'Token');
		insert dropToken;

		PageReference currPage = Page.KAAdminUserHome;
		currPage.getParameters().put('subjectName', testSubject.Name);
		currPage.getParameters().put('deleteParam', 'somethingToDelete');
		currPage.getParameters().put('deleteTopicId', testTheme.Id);
		currPage.getParameters().put('deleteSubjectId', testSubject.Id);
		currPage.getParameters().put('updateTopicId', testTheme.Id);
		currPage.getParameters().put('updateSubjectId', testSubject.Id);
		Test.setCurrentPage(currPage);

		subjectsController = new KACommonSubjectsController();
	}

	@isTest static void testTypeSubjectSelect_Success() {
		init();

		Test.startTest();

		subjectsController.tmpSubject = 'testSubject';
		subjectsController.typeSubject();

		Test.stopTest();

		System.assertEquals(subjectsController.subjects.size() > 0, true);
	}

	@isTest static void testCreateSubject_Success() {
		init();

		Test.startTest();

		subjectsController.tmpSubject = 'newTestSubject';
		subjectsController.createSubject();
		subjectsController.tmpSubject = '';
		subjectsController.typeSubject();

		Test.stopTest();

		System.assertEquals(subjectsController.subjects.size() == 2, true);
	}

	@isTest static void testCreateSubject_ExistingFailure() {
		init();

		Test.startTest();

		subjectsController.tmpSubject = 'testSubject';
		subjectsController.typeSubject();
		subjectsController.createSubject();

		Test.stopTest();

		System.assertEquals(subjectsController.subjects.size() == 1, true);
	}

	@isTest static void testCreateSubject_EmptyFailure() {
		init();

		Test.startTest();

		subjectsController.tmpSubject = '';
		subjectsController.typeSubject();
		subjectsController.createSubject();

		Test.stopTest();

		System.assertEquals(subjectsController.subjects.size() == 1, true);
	}

	@isTest static void testCreateTheme_Success() {
		init();

		Test.startTest();

		subjectsController.tmpTheme = 'newTestTheme';
		subjectsController.createTheme();

		Test.stopTest();

		System.assertEquals(subjectsController.tmpTheme == '', true);
	}

	@isTest static void testCreateThemeAnotherCondition_Success() {
		init();

		Test.startTest();

		subjectsController.tmpTheme = 'newTestTheme';
		subjectsController.tmpSubject = 'newTestSubject';
		subjectsController.createTheme();

		Test.stopTest();

		System.assertEquals(subjectsController.tmpTheme == '', true);
	}

	@isTest static void testCreateTheme_ExistingFailure() {
		init();

		Test.startTest();

		subjectsController.tmpTheme = 'testTheme';
		subjectsController.createTheme();

		Test.stopTest();

		System.assertEquals(subjectsController.notificMap.notificationMap.keyset().size() == 1, true);
	}

	@isTest static void testCreateTheme_EmptyFailure() {
		init();

		Test.startTest();

		subjectsController.tmpTheme = '';
		subjectsController.createTheme();

		Test.stopTest();

		System.assertEquals(subjectsController.notificMap.notificationMap.keyset().size() == 1, true);
	}

	@isTest static void testDeleteSubject_Success() {
		init();

		Test.startTest();

		subjectsController.typeSubject();

		insert new Subject__c(Name = 'somethingToDelete');

		subjectsController.deleteSubject();

		Test.stopTest();

		System.assertEquals(subjectsController.subjects.size() == 1, false);
	}

	@isTest static void testDeleteSubjectAnotherCondition_Success() {
		init();

		Test.startTest();

		subjectsController.typeSubject();

		insert new Subject__c(Name = 'somethingToDelete');

		subjectsController.tmpSubject = 'newTestSubject';
		subjectsController.prepareSubjectToDelete();
		subjectsController.deleteSubject();

		Test.stopTest();

		System.assertEquals(subjectsController.subjects.size() == 0, true);
	}

	@isTest static void testRedirectToThemeList_Success() {
		init();

		System.assertNotEquals(subjectsController.goToThemeList(), null);
	}

	@isTest static void testRedirectToSubjectList_Success() {
		init();

		System.assertNotEquals(subjectsController.goToSubjectList(), null);
	}

	@isTest static void testRedirectToCSVUpload_Success() {
		init();

		System.assertNotEquals(subjectsController.goToUploadCSV(), null);
	}

	@isTest static void testResetSearch_Success() {
		init();

		Test.startTest();

		subjectsController.resetSearch();

		Test.stopTest();

		System.assertEquals(subjectsController.subjects.size() == 1, true);
	}

	@isTest static void testDeletingTopic_Success() {
		init();

		Test.setMock(HttpCalloutMock.class, new KADropBoxServiceMock());

		Test.startTest();

		subjectsController.prepareTopicToDelete();
		subjectsController.deleteTopic();

		Test.stopTest();

		System.assertEquals(subjectsController.subjects.size() == 1, true);
	}

	@isTest static void testUpdatingTopic_Failure() {
		init();

		Test.setMock(HttpCalloutMock.class, new KADropBoxServiceMock());

		Test.startTest();

		subjectsController.prepareTopicToUpdate();
		subjectsController.updateTopic();
		subjectsController.resetSearch();

		Test.stopTest();

		System.assertEquals(subjectsController.subjects.size() == 1, true);
	}

	@isTest static void testUpdatingSubject_Failure() {
		init();

		Test.setMock(HttpCalloutMock.class, new KADropBoxServiceMock());

		Test.startTest();

		subjectsController.prepareSubjectToUpdate();
		subjectsController.updateSubject();
		subjectsController.resetSearch();

		Test.stopTest();

		System.assertEquals(subjectsController.subjects.size() == 1, true);
	}

	@isTest static void testUpdatingTopic_Success() {
		init();

		Test.setMock(HttpCalloutMock.class, new KADropBoxServiceMock());

		Test.startTest();

		subjectsController.prepareTopicToUpdate();
		subjectsController.tmpTheme = 'testUpdate';
		subjectsController.updateTopic();
		subjectsController.resetSearch();

		Test.stopTest();

		System.assertEquals(subjectsController.subjects.size() == 1, true);
	}

	@isTest static void testUpdatingSubject_Success() {
		init();

		Test.setMock(HttpCalloutMock.class, new KADropBoxServiceMock());

		Test.startTest();

		subjectsController.prepareSubjectToUpdate();
		subjectsController.tmpSubject = 'testUpdate';
		subjectsController.updateSubject();
		subjectsController.resetSearch();

		Test.stopTest();

		System.assertEquals(subjectsController.subjects.size() == 1, true);
	}

	@isTest static void testBackLinkInit_Success() {
		init();

		System.assert(subjectsController.backLink.contains('Admin'));
	}

}