src/objects/Answer__c.object
<CustomObject>
    <fields>
        <fullName>Question__c</fullName>
        <label>Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Answers</relationshipLabel>
        <relationshipName>Answers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Right__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Right</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Variant__c</fullName>
        <label>Variant</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Answer</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Answer #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Question__c.object
<CustomObject>
    <fields>
        <fullName>Level__c</fullName>
        <label>Level</label>
        <picklist>
            <picklistValues>
                <fullName>Junior</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Middle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Senior</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Statement__c</fullName>
        <label>Statement</label>
        <length>4096</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Theme__c</fullName>
        <label>Theme</label>
        <referenceTo>Theme__c</referenceTo>
        <relationshipLabel>Questions</relationshipLabel>
        <relationshipName>Questions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Question</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Question #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Subject__c.object
<CustomObject>
    <label>Subject</label>
    <nameField>
        <label>Subject Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subjects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Test__c.object
<CustomObject>
    <fields>
        <fullName>Subject__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subject</label>
        <referenceTo>Subject__c</referenceTo>
        <relationshipLabel>Tests</relationshipLabel>
        <relationshipName>Tests</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Test</label>
    <nameField>
        <label>Test Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Theme__c.object
<CustomObject>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <referenceTo>Subject__c</referenceTo>
        <relationshipName>Themes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Topic</label>
    <nameField>
        <label>Topic Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Topics</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/KACommonTestsControllerTest.cls
@isTest
private class KACommonTestsControllerTest {

	private static KACommonTestsController testsController;

	private static void init() {
		Subject__c testSubject = new Subject__c(Name = 'testSubject');
		insert testSubject;

		Test__c testTest = new Test__c(Name = 'testTest', Duration__c = 120, Subject__c = testSubject.Id);
		insert testTest;

		Theme__c testTheme = new Theme__c(Name = 'testTheme', Subject__c = testSubject.Id);
		insert testTheme;

		TestTheme__c testTestTheme = new TestTheme__c(Theme__c = testTheme.Id, Test__c = testTest.Id, Questions_Captured__c = 2);
		insert testTestTheme;

		Question__c testQuestion = new Question__c(Theme__c = testTheme.Id, Statement__c = 'testStatement', Level__c = 'Junior');
		insert testQuestion;

		Answer__c testFirstAnswer = new Answer__c(Question__c = testQuestion.Id, Variant__c = 'testVariant', Right__c = true);
		Answer__c testSecondAnswer = new Answer__c(Question__c = testQuestion.Id, Variant__c = 'testVariant', Right__c = false);
		insert testFirstAnswer;
		insert testSecondAnswer;

		Question__c testQuestion2 = new Question__c(Theme__c = testTheme.Id, Statement__c = 'testStatement', Level__c = 'Junior');
		insert testQuestion2;

		Answer__c testFirstAnswer2 = new Answer__c(Question__c = testQuestion2.Id, Variant__c = 'testVariant', Right__c = true);
		Answer__c testSecondAnswer2 = new Answer__c(Question__c = testQuestion2.Id, Variant__c = 'testVariant', Right__c = true);
		insert testFirstAnswer2;
		insert testSecondAnswer2;

		PageReference currPage = Page.KAAdminUserHome;
		currPage.getParameters().put('themeId', testTheme.Id);
		currPage.getParameters().put('statTheme', testTheme.Id);
		currPage.getParameters().put('testToDelete', testTest.Id);
		Test.setCurrentPage(currPage);

		testsController = new KACommonTestsController();
	}
	
	@isTest static void testTypeSubjectSelect_Success() {
		init();

		testsController.tmpSubject = 'testSubject';
		testsController.typeSubject();
		System.assertEquals(testsController.subjects.size() > 0, true);
	}

	@isTest static void testCreatingTest_Success() {
		init();

		testsController.preCreatedTest.Duration__c = 120;
		testsController.preCreatedTestTheme.Questions_Captured__c = 1;
		testsController.preCreateTest();
		testsController.createTest();
		System.assertEquals(testsController.notificMap.notificationMap.keyset().size() == 1, true);
	}

	@isTest static void testCreatingTest_QuestionsFailure() {
		init();

		testsController.preCreatedTest.Duration__c = 120;
		testsController.preCreatedTestTheme.Questions_Captured__c = -1;
		testsController.preCreateTest();
		testsController.createTest();
		System.assertEquals(testsController.notificMap.notificationMap.keyset().size() == 1, true);
	}

	@isTest static void testCreatingTest_NullQuestionsFailure() {
		init();

		testsController.preCreatedTest.Duration__c = 120;
		testsController.preCreatedTestTheme.Questions_Captured__c = null;
		testsController.preCreateTest();
		testsController.createTest();
		System.assertEquals(testsController.notificMap.notificationMap.keyset().size() == 1, true);
	}

	@isTest static void testCreatingTest_ThemeQuestionsFailure() {
		init();

		testsController.preCreatedTest.Duration__c = 120;
		testsController.preCreatedTestTheme.Questions_Captured__c = 10;
		testsController.preCreateTest();
		testsController.createTest();
		System.assertEquals(testsController.notificMap.notificationMap.keyset().size() == 1, true);
	}

	@isTest static void testCreatingTest_DurationFailure() {
		init();

		testsController.preCreatedTest.Duration__c = -120;
		testsController.preCreatedTestTheme.Questions_Captured__c = 1;
		testsController.preCreateTest();
		testsController.createTest();
		System.assertEquals(testsController.notificMap.notificationMap.keyset().size() == 1, true);
	}

	@isTest static void testCreatingTest_NullDurationFailure() {
		init();

		testsController.preCreatedTest.Duration__c = null;
		testsController.preCreatedTestTheme.Questions_Captured__c = 1;
		testsController.preCreateTest();
		testsController.createTest();
		System.assertEquals(testsController.notificMap.notificationMap.keyset().size() == 1, true);
	}

	@isTest static void testCreatingTest_EqualTestFailure() {
		init();

		testsController.preCreatedTest.Duration__c = 120;
		testsController.preCreatedTestTheme.Questions_Captured__c = 1;
		testsController.preCreateTest();
		testsController.preCreatedTest.Name = 'testTest';
		testsController.createTest();
		System.assertEquals(testsController.notificMap.notificationMap.keyset().size() == 1, true);
	}

	@isTest static void testCreatingTest_SubjectForTestFailure() {
		init();

		testsController.preCreatedTest.Duration__c = 120;
		testsController.preCreatedTestTheme.Questions_Captured__c = 1;
		testsController.preCreateTest();
		testsController.testSubjectName = 'failure';
		testsController.createTest();
		System.assertEquals(testsController.notificMap.notificationMap.keyset().size() == 1, true);
	}
	
	@isTest static void testCreatingThemeStatistic_Success() {
		init();

		testsController.createThemeStatistic();
		System.assertNotEquals(testsController.themeStatistic.size() == 0, true);
	}

	@isTest static void testClearingThemeStatistic_Success() {
		init();

		testsController.createThemeStatistic();
		testsController.clearThemeStatistic();
		System.assertEquals(testsController.themeStatistic.size() == 0, true);
	}

	@isTest static void testDeleteingTest_Success() {
		init();

		testsController.deleteTest();
		System.assertEquals(testsController.subjects.size() == 1, true);
	}

	@isTest static void testSubjectsListRedirecting_Success() {
		init();

		System.assertNotEquals(testsController.goToSubjectList(), null);
	}

	@isTest static void testUploadCSVRedirecting_Success() {
		init();

		System.assertNotEquals(testsController.goToUploadCSV(), null);
	}

	@isTest static void testResetSearch_Success() {
		init();

		testsController.resetSearch();
		System.assertEquals(testsController.subjects.size() == 1, true);
	}
	
}