src/objects/Answer__c.object
<CustomObject>
    <fields>
        <fullName>Question__c</fullName>
        <label>Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Answers</relationshipLabel>
        <relationshipName>Answers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Right__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Right</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Variant__c</fullName>
        <label>Variant</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Answer</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Answer #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Browser__c.object
<CustomObject>
    <fields>
        <fullName>Employee__c</fullName>
        <label>Employee</label>
        <referenceTo>Employee__c</referenceTo>
        <relationshipLabel>Browsers</relationshipLabel>
        <relationshipName>Browsers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Identifier__c</fullName>
        <label>Identifier</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Browser</label>
    <nameField>
        <displayFormat>BI-{0000}</displayFormat>
        <label>Browser #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Browsers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Employee__c.object
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>Username</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Pass_History__c.object
<CustomObject>
    <fields>
        <fullName>Employee__c</fullName>
        <label>Employee</label>
        <referenceTo>Employee__c</referenceTo>
        <relationshipLabel>Pass Results</relationshipLabel>
        <relationshipName>Pass_Results</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Result__c</fullName>
        <label>Result</label>
        <precision>4</precision>
        <required>true</required>
        <scale>1</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Test__c</fullName>
        <label>Test</label>
        <referenceTo>Test__c</referenceTo>
        <relationshipLabel>Pass Results</relationshipLabel>
        <relationshipName>Pass_Results</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Pass History</label>
    <nameField>
        <displayFormat>PR-{00000}</displayFormat>
        <label>Pass History #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pass Results</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Question__c.object
<CustomObject>
    <fields>
        <fullName>Statement__c</fullName>
        <label>Statement</label>
        <length>4096</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Theme__c</fullName>
        <label>Theme</label>
        <referenceTo>Theme__c</referenceTo>
        <relationshipLabel>Questions</relationshipLabel>
        <relationshipName>Questions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Question</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Question #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Subject__c.object
<CustomObject>
    <label>Subject</label>
    <nameField>
        <label>Subject Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subjects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Test__c.object
<CustomObject>
    <fields>
        <fullName>Subject__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subject</label>
        <referenceTo>Subject__c</referenceTo>
        <relationshipLabel>Tests</relationshipLabel>
        <relationshipName>Tests</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Test</label>
    <nameField>
        <label>Test Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Theme__c.object
<CustomObject>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <referenceTo>Subject__c</referenceTo>
        <relationshipName>Themes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Topic</label>
    <nameField>
        <label>Topic Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Topics</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/KATestPassingController.cls
public with sharing class KATestPassingController {

	public List<String> multipleAnswers { get; set; }
	public String singleAnswer { get; set; }

	public List<Question__c> questions { get; private set; }
	public Map<String, Boolean> variants { get; private set; }
	public Integer currentQuestion { get; private set; }
	public Integer totalQuestionsNum { get; private set; }
	public String questionType { get; private set; }

	public Boolean isEnableBlock1 { get; private set; }
	public Boolean isEnableBlock2 { get; private set; }

	public List<List<String>> appliedAnswers { get; private set; }

	private List<String> subAppliedAnswer { private get; private set; }
	private String userId { private get; private set; }
	private String testId { private get; private set; }
	private PageReference currentPage;


	public KATestPassingController() {
		currentQuestion = 0;

		multipleAnswers = new List<String>();
		variants = new Map<String, Boolean>();

		currentPage = ApexPages.currentPage();
		testId = currentPage.getParameters().get('test');

		Cookie tmpCookie = currentPage.getCookies().get('Identifier');

		if (testId != null && tmpCookie != null) {
			List<Browser__c> tmpBrowsers = [
				SELECT Employee__r.Id
				FROM Browser__c
				WHERE Identifier__c = :tmpCookie.getValue()
				LIMIT 1
			];
			if ( ! tmpBrowsers.isEmpty()) {
				userId = tmpBrowsers.get(0).Employee__r.Id;

				List<TestTheme__c> correspThemes = [
					SELECT Theme__r.Id
					FROM TestTheme__c
					WHERE Test__r.Id = :testId
				];

				if ( ! correspThemes.isEmpty()) {
					questions = [
						SELECT Id, Statement__c, Theme__r.Subject__r.Name, Theme__r.Name,
						(
							SELECT Variant__c, Right__c
							FROM Answers__r
						)
						FROM Question__c
						WHERE Theme__r.Id = :correspThemes.get(0).Theme__r.Id
						LIMIT 50000
					];
					totalQuestionsNum = questions.size();

					appliedAnswers = new List<List<String>>();
					for (Integer i = 0; i < totalQuestionsNum; i++) {
						appliedAnswers.add(new List<String>());
					}

					subAppliedAnswer = new String[1];
					variants = getVariants(currentQuestion);
				}
			}
		}
		this.isEnableBlock1 = true;
		this.isEnableBlock2 = false;
	}

	public PageReference goHome() {
		return new PageReference('/apex/KARegularUserHome');
	}

	public List<SelectOption> getVariantOptions() {
		List<SelectOption> resultVariants = new List<SelectOption>();
		for (String variantKey : variants.keySet()) {
			resultVariants.add(new SelectOption(variantKey, variantKey));
		}
		return resultVariants;
	}

	public void goToPrev() {
		doSingleTransfer(false);
	}

	public void goToNext() {
		doSingleTransfer(true);
	}

	public void goToFinish() {
		doSingleTransfer(null);
		this.isEnableBlock1 = false;
		this.isEnableBlock2 = true;

	}

	public void goToQuestions() {
		this.isEnableBlock1 = true;
		this.isEnableBlock2 = false;

		String newCurrQuest = ApexPages.currentPage().getParameters().get('questOnEdit');
		currentQuestion = Integer.valueOf(newCurrQuest);
		variants = getVariants(currentQuestion);
	}

	public PageReference finishTest() {
		Employee__c currentEmployee = [
			SELECT Id
			FROM Employee__c
			WHERE Id = :userId
			LIMIT 1
		];
		Test__c currentTest = [
			SELECT Id
			FROM Test__c
			WHERE Id = :testId
			LIMIT 1
		];
		List<Pass_History__c> oldHistory = [
			SELECT Id
			FROM Pass_History__c
			WHERE Test__r.Id = :testId AND Employee__r.Id = :userId
		];
		delete oldHistory;

		Pass_History__c newestResult = new Pass_History__c(Employee__c = currentEmployee.Id, Test__c = currentTest.Id, Result__c = getResults());
		insert newestResult;

		return new PageReference('/apex/KARegularUserHome');
	}

	private Map<String, Boolean> getVariants(Integer questionPosition) {
		List<Answer__c> tmpVariants = [
			SELECT Variant__c, Right__c
			FROM Answer__c
			WHERE Question__r.Id = :questions[questionPosition].Id
		];
		Map<String, Boolean> resultVariants = new Map<String, Boolean>();
		{
			Integer rights = 0;
			for (Answer__c answer : tmpVariants) {
				resultVariants.put(answer.Variant__c, answer.Right__c);
				if (answer.Right__c == true) {
					rights++;
				}
			}
			if (rights > 1) {
				questionType = 'multiple';
				multipleAnswers = appliedAnswers.get(questionPosition);
			}
			else {
				questionType = 'single';
				if (appliedAnswers.get(questionPosition).size() == 1) {
					singleAnswer = appliedAnswers.get(questionPosition).get(0);
				}
			}
		}
		return resultVariants;
	}

	private Map<String, Boolean> getRightVariants(Integer questionPosition) {
		List<Answer__c> tmpVariants = questions.get(questionPosition).Answers__r;
		for (Integer i = 0; i < tmpVariants.size(); i++) {
			if ( ! tmpVariants.get(i).Right__c) {
				tmpVariants.remove(i);
				i--;
			}
		}
		Map<String, Boolean> resultVariants = new Map<String, Boolean>();
		{
			for (Answer__c answer : tmpVariants) {
				resultVariants.put(answer.Variant__c, answer.Right__c);
			}
		}
		return resultVariants;
	}

	private void doSingleTransfer(Boolean direction) {
		if (questionType == 'multiple') {
			appliedAnswers.set(currentQuestion, new List<String>(multipleAnswers));
			multipleAnswers.clear();
		}
		else if (questionType == 'single') {
			subAppliedAnswer[0] = singleAnswer;
			appliedAnswers.set(currentQuestion, new List<String>(subAppliedAnswer));
			singleAnswer = '';
		}
		if (direction != null) {
			if (direction) {
				currentQuestion++;
			}
			else {
				currentQuestion--;
			}
			variants = getVariants(currentQuestion);
		}
		else {

		}
	}

	private Double getResults() {
		Map<String, Boolean> resultVariants = new Map<String, Boolean>();
		List<String> resultAppliedAnswers = new List<String>();
		Integer rightAnswers = 0;
		for (Integer i = 0; i < totalQuestionsNum; i++) {
			resultVariants = getRightVariants(i);
			resultAppliedAnswers = appliedAnswers.get(i);

			Boolean isRight = true;
			if (resultVariants.size() == resultAppliedAnswers.size()) {
				for (String resultAnswer : resultAppliedAnswers) {
					if (resultVariants.get(resultAnswer) == null || ! resultVariants.get(resultAnswer)) {
						isRight = false;
						break;
					}
				}
				if (isRight) {
					rightAnswers++;
				}
			}
		}
		return 100 * rightAnswers / totalQuestionsNum;
	}

}