src/objects/Answer__c.object
<CustomObject>
    <fields>
        <fullName>Question__c</fullName>
        <label>Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Answers</relationshipLabel>
        <relationshipName>Answers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Right__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Right</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Variant__c</fullName>
        <label>Variant</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Answer</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Answer #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Question__c.object
<CustomObject>
    <fields>
        <fullName>Level__c</fullName>
        <label>Level</label>
        <picklist>
            <picklistValues>
                <fullName>Junior</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Middle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Senior</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Statement__c</fullName>
        <label>Statement</label>
        <length>4096</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Theme__c</fullName>
        <label>Theme</label>
        <referenceTo>Theme__c</referenceTo>
        <relationshipLabel>Questions</relationshipLabel>
        <relationshipName>Questions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Question</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Question #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Theme__c.object
<CustomObject>
    <label>Topic</label>
    <nameField>
        <label>Topic Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Topics</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/KAImportQuestionsCSVController.cls
public with sharing class KAImportQuestionsCSVController {
public Blob csvFileBody{get;set;}
public String csvAsString{get;set;}
public String[] csvFileLines{get;set;}
public List<Question__c> quelist{get;set;}
public List<List<Answer__c>> rightAnswers{get;set;}
public List<List<Answer__c>> wrongAnswers{get;set;}

	public KAImportQuestionsCSVController() {
		csvFileLines = new String[]{};
		quelist = new List<Question__c>();
		rightAnswers = new List<List<Answer__c>>();
		wrongAnswers = new List<List<Answer__c>>();
	}

	public void importCSVFile() {

		quelist.clear();
		csvAsString = csvFileBody.toString();
		csvFileLines = csvAsString.split('\n');



		for (Integer i = 1; i < csvFileLines.size(); i++) {
			Question__c question = new Question__c();
			String[] csvRecordData = csvFileLines[i].split(',');
			if (csvRecordData.size() == 4) {
				question.Statement__c = csvRecordData[0];
				question.Level__c = csvRecordData[1];

				List<Answer__c> tmpRightAnswerList = new List<Answer__c>();
				if ( ! String.isEmpty(csvRecordData[2])) {
					for (String answerName : csvRecordData[2].split(';')) {
						tmpRightAnswerList.add(new Answer__c(Variant__c = answerName, Right__c = true));
					}
					rightAnswers.add(tmpRightAnswerList);
				}

				List<Answer__c> tmpWrongAnswerList = new List<Answer__c>();
				if (csvRecordData[3].split(';').size() !=0) {
					for (String answerName : csvRecordData[3].split(';')) {//
						tmpWrongAnswerList.add(new Answer__c(Variant__c = answerName));
					}
					wrongAnswers.add(tmpWrongAnswerList);
				}

				question.Theme__c = [
					SELECT Id
					FROM Theme__c
					LIMIT 1
				][0].Id;
				quelist.add(question);
			}
	   	}

  	}

  	public void insertToDatabase () {
		if ( ! quelist.isEmpty()) {
			insert quelist;
		}
		for (Integer i = 0; i < quelist.size(); i++) {
			for (Integer j = 0; j < rightAnswers[i].size(); j++) {
				rightAnswers[i][j].Question__c = quelist[i].Id;
			}
			for (Integer j = 0; j < wrongAnswers[i].size(); j++) {
				wrongAnswers[i][j].Question__c = quelist[i].Id;
			}
		}
		for (List<Answer__c> answer : rightAnswers) {
			insert answer;
		}
		for (List<Answer__c> answer : wrongAnswers) {
			insert answer;
		}
		quelist.clear();
  }
}