src/objects/Browser__c.object
<CustomObject>
    <fields>
        <fullName>Employee__c</fullName>
        <label>Employee</label>
        <referenceTo>Employee__c</referenceTo>
        <relationshipLabel>Browsers</relationshipLabel>
        <relationshipName>Browsers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Identifier__c</fullName>
        <label>Identifier</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Browser</label>
    <nameField>
        <displayFormat>BI-{0000}</displayFormat>
        <label>Browser #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Browsers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Employee__c.object
<CustomObject>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsAdmin__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsAdmin</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <label>Employee</label>
    <nameField>
        <label>Username</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/KANavigationBarController.cls
public with sharing class KANavigationBarController {

	public Browser__c browserUser { get; private set; }

	private String username { private get; private set; }
	private PageReference currentPage { private get; private set; }

	public KANavigationBarController() {
		currentPage = ApexPages.currentPage();
		Cookie tmpCookie = currentPage.getCookies().get('KALogin');
		if (tmpCookie != null) {
			username = tmpCookie.getValue();
		}
	}

	public PageReference onLoad() {
		if (getLoginCookie() != null) {
			List<Browser__c> browsers = [
				SELECT Identifier__c, Employee__r.Name, Employee__r.Password__c, Employee__r.IsAdmin__c, Employee__r.First_Name__c, Employee__r.Last_Name__c
				FROM Browser__c
				WHERE Identifier__c = :getLoginCookie().getValue()
				LIMIT 1
			];
			browserUser = ! browsers.isEmpty() ? browsers.get(0) : null;
			if (browserUser != null) {
				return null;
			}
		}
		return new PageReference('/apex/KALogin');
	}

	public PageReference goHome() {
		return null;
	}

	public PageReference makeLogout() {
		ApexPages.currentPage().setCookies(
			new Cookie[] {
				new Cookie('Identifier', '', null, 0, false)
			}
		);
		return new PageReference('/apex/KALogin');
	}

	private void setLoginCookie(String id) {
		currentPage.setCookies(
		    new Cookie[] {
		        new Cookie('Identifier', id, null, 1000, false)
		    }
		);
	}

	private Cookie getLoginCookie() {
		return currentPage.getCookies().get('Identifier');
	}
}