src/objects/Browser__c.object
<CustomObject>
    <fields>
        <fullName>Employee__c</fullName>
        <label>Employee</label>
        <referenceTo>Employee__c</referenceTo>
        <relationshipLabel>Browsers</relationshipLabel>
        <relationshipName>Browsers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Identifier__c</fullName>
        <label>Identifier</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Browser</label>
    <nameField>
        <displayFormat>BI-{0000}</displayFormat>
        <label>Browser #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Browsers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Employee__c.object
<CustomObject>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Employee</label>
    <nameField>
        <label>Username</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Employee_Task__c.object
<CustomObject>
    <fields>
        <fullName>Employee__c</fullName>
        <label>Employee</label>
        <referenceTo>Employee__c</referenceTo>
        <relationshipName>EmployeeTasks</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Task__c</fullName>
        <label>Task</label>
        <referenceTo>Task__c</referenceTo>
        <relationshipName>EmployeeTasks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Employee Task</label>
    <nameField>
        <displayFormat>ET-{00000}</displayFormat>
        <label>Employee Task #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employee Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Pass_History__c.object
<CustomObject>
    <fields>
        <fullName>Employee__c</fullName>
        <label>Employee</label>
        <referenceTo>Employee__c</referenceTo>
        <relationshipLabel>Pass Results</relationshipLabel>
        <relationshipName>Pass_Results</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Test__c</fullName>
        <label>Test</label>
        <referenceTo>Test__c</referenceTo>
        <relationshipLabel>Pass Results</relationshipLabel>
        <relationshipName>Pass_Results</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Pass History</label>
    <nameField>
        <displayFormat>PR-{00000}</displayFormat>
        <label>Pass History #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pass Results</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Task__c.object
<CustomObject>
    <fields>
        <fullName>Test__c</fullName>
        <label>Test</label>
        <referenceTo>Test__c</referenceTo>
        <relationshipLabel>Tasks</relationshipLabel>
        <relationshipName>Tasks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Task</label>
    <nameField>
        <displayFormat>T-{00000}</displayFormat>
        <label>Task #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Test__c.object
<CustomObject>
    <label>Test</label>
    <nameField>
        <label>Test Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/KARegularHomeControllerTest.cls
@isTest
private class KARegularHomeControllerTest {

	private static KARegularHomeController regularController;

	private static void init() {
		Employee__c testEmployee = new Employee__c(Name = 'test@test.com', First_Name__c = 'testFirstName');
		insert testEmployee;

		Browser__c testBrowser = new Browser__c(Employee__c = testEmployee.Id, Identifier__c = 'testIdentifier');
		insert testBrowser;

		Test__c testTest = new Test__c(Name = 'testTest');
		insert testTest;

		Task__c testTask = new Task__c(Test__c = testTest.Id);
		insert testTask;

		Pass_History__c testHistory = new Pass_History__c(Test__c = testTest.Id, Employee__c = testEmployee.Id);
		insert testHistory;

		Employee_Task__c testEmploTask = new Employee_Task__c(Employee__c = testEmployee.Id, Task__c = testTask.Id);
		insert testEmploTask;

		PageReference currPage = Page.KARegularUserHome;
		currPage.setCookies(
			new Cookie[] {
				new Cookie('Identifier', testBrowser.Identifier__c, null, 1000, false)
			}
		);
		Test.setCurrentPage(currPage);

		regularController = new KARegularHomeController();
	}

	@isTest static void testConstruction_Success() {
		init();

		System.assertNotEquals(regularController.upcomingTests, null);
	}

	@isTest static void testLaunchingTest_Success() {
		init();

		regularController.launchedTestId = 'success';
		System.assertNotEquals(regularController.launchTest(), null);
	}

	@isTest static void testLaunchingTest_Failure() {
		init();

		System.assertEquals(regularController.launchTest(), null);
	}

}