src/objects/Browser__c.object
<CustomObject>
    <fields>
        <fullName>Employee__c</fullName>
        <label>Employee</label>
        <referenceTo>Employee__c</referenceTo>
        <relationshipLabel>Browsers</relationshipLabel>
        <relationshipName>Browsers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Identifier__c</fullName>
        <label>Identifier</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Browser</label>
    <nameField>
        <displayFormat>BI-{0000}</displayFormat>
        <label>Browser #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Browsers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Employee__c.object
<CustomObject>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsAdmin__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsAdmin</label>
        <type>Checkbox</type>
    </fields>
    <label>Employee</label>
    <nameField>
        <label>Username</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/KANavigationBarControllerTest.cls
@isTest
private class KANavigationBarControllerTest {

	private static KANavigationBarController navigationController;

	private static void init() {
		Employee__c testEmployee = new Employee__c(Name = 'testName', First_Name__c = 'testFirstName');
		insert testEmployee;

		Browser__c testBrowser = new Browser__c(Employee__c = testEmployee.Id, Identifier__c = 'testIdentifier');
		insert testBrowser;

		PageReference currPage = Page.KARegularUserHome;
		currPage.setCookies(
			new Cookie[] {
				new Cookie('Identifier', testBrowser.Identifier__c, null, 1000, false)
			}
		);
		Test.setCurrentPage(currPage);

		navigationController = new KANavigationBarController();
	}

	@isTest static void testUserPageConstruction_Success() {
		init();

		System.assertNotEquals(navigationController.browserUser, null);
	}

	@isTest static void testUsersRedirection_Success() {
		init();

		System.assertNotEquals(navigationController.goToUsers(), null);
	}

	@isTest static void testTestsRedirection_Success() {
		init();

		System.assertNotEquals(navigationController.goToTests(), null);
	}

	@isTest static void testDataRedirection_Success() {
		init();

		System.assertNotEquals(navigationController.goToData(), null);
	}

	@isTest static void testOnLoadStartPage_Success() {
		init();

		System.assertEquals(navigationController.onLoad(), null);
	}

	@isTest static void testOnLoadNotStartPage_Success() {
		init();
		PageReference currPage = Page.KACreateNewPassword;
		Test.setCurrentPage(currPage);

		System.assertNotEquals(navigationController.onLoad(), null);
	}

	@isTest static void testLogout_Success() {
		init();

		System.assertNotEquals(navigationController.makeLogout(), null);
	}

	@isTest static void testRegularHomeRedirection_Success() {
		init();

		System.assertEquals(navigationController.goHome().getUrl().toUpperCase().contains('REGULAR'), true);
	}

	@isTest static void testAdminHomeRedirection_Success() {
		init();

		List<Employee__c> usersToDeleteList = [
			SELECT Id
			FROM Employee__c
		];
		delete usersToDeleteList;

		Employee__c testEmployee = new Employee__c(Name = 'testName', First_Name__c = 'testFirstName', IsAdmin__c = true);
		insert testEmployee;

		Browser__c testBrowser = new Browser__c(Employee__c = testEmployee.Id, Identifier__c = 'testIdentifier');
		insert testBrowser;

		PageReference currPage = Page.KARegularUserHome;
		currPage.setCookies(
			new Cookie[] {
				new Cookie('Identifier', testBrowser.Identifier__c, null, 1000, false)
			}
		);
		Test.setCurrentPage(currPage);

		navigationController = new KANavigationBarController();

		System.assertEquals(navigationController.goHome().getUrl().toUpperCase().contains('ADMIN'), true);
	}

}