src/objects/Employee__c.object
<CustomObject>
    <fields>
        <fullName>Action_Hash__c</fullName>
        <label>Action Hash</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Waiting_Reset__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Waiting Reset</label>
        <type>Checkbox</type>
    </fields>
    <label>Employee</label>
    <nameField>
        <label>Username</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Employee_Task__c.object
<CustomObject>
    <fields>
        <fullName>Employee__c</fullName>
        <label>Employee</label>
        <referenceTo>Employee__c</referenceTo>
        <relationshipName>EmployeeTasks</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>IsEmailQueue__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsEmailQueue</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Task__c</fullName>
        <label>Task</label>
        <referenceTo>Task__c</referenceTo>
        <relationshipName>EmployeeTasks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Employee Task</label>
    <nameField>
        <displayFormat>ET-{00000}</displayFormat>
        <label>Employee Task #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employee Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Task__c.object
<CustomObject>
    <fields>
        <fullName>AssignTime__c</fullName>
        <label>AssignTime</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Test__c</fullName>
        <label>Test</label>
        <referenceTo>Test__c</referenceTo>
        <relationshipLabel>Tasks</relationshipLabel>
        <relationshipName>Tasks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Task</label>
    <nameField>
        <displayFormat>T-{00000}</displayFormat>
        <label>Task #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Test__c.object
<CustomObject>
    <label>Test</label>
    <nameField>
        <label>Test Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/KAEmailHandlerTest.cls
@isTest
private class KAEmailHandlerTest {

	private static KAEmailHandler emailHandler;

	private static void init() {
		Employee__c testEmployee = new Employee__c(Name = 'test@mail.ru', First_Name__c = 'testFName', Waiting_Reset__c = true, Action_Hash__c = 'testHash');
		insert testEmployee;

		Test__c testTest = new Test__c(Name = 'testTest');
		insert testTest;

		Task__c testTask = new Task__c(Test__c = testTest.Id, AssignTime__c = Datetime.now() + 200);
		insert testTask;

		Employee_Task__c testEmploTask = new Employee_Task__c(Task__c = testTask.Id, Employee__c = testEmployee.Id, IsEmailQueue__c = true);
		insert testEmploTask;

		emailHandler = new KAEmailHandler();
	}

	@isTest static void testExecute() {
		init();

		Test.startTest();

		emailHandler.sendAction();
		Employee_Task__c assertEmploTask = [
			SELECT IsEmailQueue__c
			FROM Employee_Task__c
			LIMIT 1
		];

		Test.stopTest();

		System.assertEquals(assertEmploTask.IsEmailQueue__c, false);
	}

}