src/objects/Employee__c.object
<CustomObject>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Employee</label>
    <nameField>
        <label>Username</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/KAUsersBoardController.cls
public with sharing class KAUsersBoardController {

	public List<Employee__c> users { get; private set; }

	public KAUsersBoardController() {
		users = [
			SELECT First_Name__c, Last_Name__c
			FROM Employee__c
			LIMIT 50000
		];
	}
	
	public PageReference goToUsers() {
		//Employee__c currentEmployee = [
		//	SELECT Id
		//	FROM Employee__c
		//	WHERE Name = :username
		//	LIMIT 1
		//];
	return new PageReference('/apex/KAStatistic?userId=' + ApexPages.currentPage().getParameters().get('userId'));	
	}
}