src/objects/Employee__c.object
<CustomObject>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <label>Employee</label>
    <nameField>
        <label>Username</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Pass_History__c.object
<CustomObject>
    <fields>
        <fullName>Employee__c</fullName>
        <label>Employee</label>
        <referenceTo>Employee__c</referenceTo>
        <relationshipLabel>Pass Results</relationshipLabel>
        <relationshipName>Pass_Results</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Result__c</fullName>
        <label>Result</label>
        <precision>4</precision>
        <required>true</required>
        <scale>1</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Test__c</fullName>
        <label>Test</label>
        <referenceTo>Test__c</referenceTo>
        <relationshipLabel>Pass Results</relationshipLabel>
        <relationshipName>Pass_Results</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Pass History</label>
    <nameField>
        <displayFormat>PR-{00000}</displayFormat>
        <label>Pass History #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pass Results</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Subject__c.object
<CustomObject>
    <label>Subject</label>
    <nameField>
        <label>Subject Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subjects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Test__c.object
<CustomObject>
    <fields>
        <fullName>Subject__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subject</label>
        <referenceTo>Subject__c</referenceTo>
        <relationshipLabel>Tests</relationshipLabel>
        <relationshipName>Tests</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Test</label>
    <nameField>
        <label>Test Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/KAStatisticControllerTest.cls
@isTest
private class KAStatisticControllerTest {

	private static KAStatisticController testStatContr;

	private static void init() {
		Employee__c testEmployee = new Employee__c(First_Name__c = 'testName', Last_Name__c = 'testLastName', Password__c = 'testPass');
		insert testEmployee;

		Subject__c testSubject1 = new Subject__c();
		insert testSubject1;

		Subject__c testSubject2 = new Subject__c();
		insert testSubject2;

		Test__c test1 = new Test__c(Name = 'test1', Subject__c = testSubject1.Id);
		insert test1;

		Test__c test2 = new Test__c(Name = 'test2', Subject__c = testSubject2.Id);
		insert test2;

		Double testResult1 = 66.5;
		Double testResult2 = 10;
		Pass_History__c testHistory1 = new Pass_History__c(Employee__c = testEmployee.Id, Result__c = testResult1, Test__c = test1.Id );
		insert testHistory1;

		Pass_History__c testHistory2 = new Pass_History__c(Employee__c = testEmployee.Id, Result__c = testResult2, Test__c = test2.Id );
		insert testHistory2;

		PageReference currPage = Page.KAStatistic;
  		currPage.getParameters().put('userId', testEmployee.Id);
  		Test.setCurrentPage(currPage);
		testStatContr = new KAStatisticController();

	}

	@isTest static void testRefreshRecentResults() {
		init();
		testStatContr.refreshRecentResults();
		Integer tableSize = testStatContr.recentResults.size();
		System.assertEquals(2, tableSize);

	}

	@isTest static void testOrderByCreatedOn() {
		init();
		testStatContr.orderByCreatedOn();
		Datetime  testItem1 = testStatContr.recentResults.get(0).createdDate;
		testStatContr.orderByCreatedOn();
		Datetime  testItem2 = testStatContr.recentResults.get(0).createdDate;
		System.assertEquals(testItem1 <= testItem2, true);
	}


	@isTest static void testOrderBySubject() {
		init();
		testStatContr.orderBySubject();
		String  testName1 = testStatContr.recentResults.get(0).Test__r.Subject__r.Name;
		testStatContr.orderBySubject();
		String  testName2 = testStatContr.recentResults.get(0).Test__r.Subject__r.Name;
		System.assertNotEquals(testName1, testName2);

	}

	@isTest static void testOrderByTestTitle() {
		init();
		testStatContr.orderByTestTitle();
		String  testName1 = testStatContr.recentResults.get(0).Test__r.Name;
		testStatContr.orderByTestTitle();
		String  testName2 = testStatContr.recentResults.get(0).Test__r.Name;
		System.assertNotEquals(testName1, testName2);

	}

	@isTest static void testOrderByPassResult() {
		init();
		testStatContr.orderByPassResult();
		Double  testName1 = testStatContr.recentResults.get(0).Result__c;
		testStatContr.orderByPassResult();
		Double  testName2 = testStatContr.recentResults.get(0).Result__c;
		System.assertNotEquals(testName1, testName2);

	}


}