src/objects/Employee__c.object
<CustomObject>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Employee</label>
    <nameField>
        <label>Username</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Employee_Task__c.object
<CustomObject>
    <fields>
        <fullName>Employee__c</fullName>
        <label>Employee</label>
        <referenceTo>Employee__c</referenceTo>
        <relationshipName>EmployeeTasks</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Task__c</fullName>
        <label>Task</label>
        <referenceTo>Task__c</referenceTo>
        <relationshipName>EmployeeTasks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Employee Task</label>
    <nameField>
        <displayFormat>ET-{00000}</displayFormat>
        <label>Employee Task #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employee Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Pass_History__c.object
<CustomObject>
    <fields>
        <fullName>Employee__c</fullName>
        <label>Employee</label>
        <referenceTo>Employee__c</referenceTo>
        <relationshipLabel>Pass Results</relationshipLabel>
        <relationshipName>Pass_Results</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Test__c</fullName>
        <label>Test</label>
        <referenceTo>Test__c</referenceTo>
        <relationshipLabel>Pass Results</relationshipLabel>
        <relationshipName>Pass_Results</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Pass History</label>
    <nameField>
        <displayFormat>PR-{00000}</displayFormat>
        <label>Pass History #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pass Results</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Task__c.object
<CustomObject>
    <fields>
        <fullName>AssignTime__c</fullName>
        <label>AssignTime</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Test__c</fullName>
        <label>Test</label>
        <referenceTo>Test__c</referenceTo>
        <relationshipLabel>Tasks</relationshipLabel>
        <relationshipName>Tasks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Task</label>
    <nameField>
        <displayFormat>T-{00000}</displayFormat>
        <label>Task #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Test__c.object
<CustomObject>
    <label>Test</label>
    <nameField>
        <label>Test Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/KAAdminHomeControllerTest.cls
@isTest
private class KAAdminHomeControllerTest {

	private static KAAdminHomeController adminController;

	private static void init() {
		Employee__c testEmployee = new Employee__c(Name = 'test@test.com', First_Name__c = 'testFirstName');
		insert testEmployee;

		Test__c testTest = new Test__c(Name = 'testTest');
		insert testTest;

		Task__c testTask = new Task__c(Test__c = testTest.Id);
		insert testTask;

		Pass_History__c testHistory = new Pass_History__c(Test__c = testTest.Id, Employee__c = testEmployee.Id);
		insert testHistory;

		Employee_Task__c testEmploTask = new Employee_Task__c(Employee__c = testEmployee.Id, Task__c = testTask.Id);
		insert testEmploTask;

		PageReference currPage = Page.KAAdminUserHome;
		currPage.getParameters().put('chosenEmployee', testEmployee.Id);
		currPage.getParameters().put('chosenTest', testTest.Id);
		Test.setCurrentPage(currPage);

		adminController = new KAAdminHomeController();

		adminController.tmpEmployee = testEmployee.First_Name__c;
		adminController.tmpTest = testTest.Name;
	}

	@isTest static void testSwitchEmailing_On() {
		init();

		adminController.switchEmailing();
		List<CronTrigger> scheduledTriggers = [
			SELECT Id
			FROM CronTrigger
		];
		System.assertEquals(scheduledTriggers.size() > 0, true);
	}

	@isTest static void testSwitchEmailing_Off() {
		init();

		adminController.switchEmailing();
		adminController.switchEmailing();

		List<CronTrigger> scheduledTriggers = [
			SELECT Id
			FROM CronTrigger
		];
		System.assertEquals(scheduledTriggers.size() > 0, false);
	}

	@isTest static void testRefreshingTasks_Success() {
		init();

		adminController.refreshRecentTasks();
		System.assertEquals(adminController.recentTasks.size(), 1);
	}

	@isTest static void testRefreshingResults_Success() {
		init();

		adminController.refreshRecentResults();
		System.assertEquals(adminController.recentResults.size(), 1);
	}

	@isTest static void testTypingEmployee_Success() {
		init();

		adminController.typeEmployee();
		System.assertEquals(adminController.employees.size(), 1);
	}

	@isTest static void testTypingTest_Success() {
		init();

		adminController.typeTest();
		System.assertEquals(adminController.tests.size(), 1);
	}

	@isTest static void testChoosingEmployee_Success() {
		init();

		adminController.chooseEmployee();
		System.assertEquals(adminController.employees.size(), 0);
	}

	@isTest static void testChoosingTest_Success() {
		init();

		adminController.chooseTest();
		System.assertEquals(adminController.tests.size(), 0);
	}

	@isTest static void testCreatingTask_Success() {
		init();

		adminController.chooseEmployee();
		adminController.chooseTest();
		adminController.preCreatedTask.AssignTime__c = Datetime.now() + 10;
		adminController.createNewTask();

		System.assertNotEquals(adminController.notificMap.notificationMap.get('success'), null);
	}

	@isTest static void testCreatingTask_TestFailure() {
		init();

		adminController.chooseEmployee();
		adminController.preCreatedTask.AssignTime__c = Datetime.now() + 10;
		adminController.createNewTask();

		System.assertNotEquals(adminController.notificMap.notificationMap.get('danger'), null);
	}

	@isTest static void testCreatingTask_EmployeeFailure() {
		init();

		adminController.chooseTest();
		adminController.preCreatedTask.AssignTime__c = Datetime.now() + 10;
		adminController.createNewTask();

		System.assertNotEquals(adminController.notificMap.notificationMap.get('danger'), null);
	}

	@isTest static void testCreatingTask_DateFailure() {
		init();

		adminController.chooseEmployee();
		adminController.chooseTest();
		adminController.preCreatedTask.AssignTime__c = Datetime.now() - 10;
		adminController.createNewTask();

		System.assertNotEquals(adminController.notificMap.notificationMap.get('danger'), null);
	}

	@isTest static void testCreatingTask_ValidationFailure() {
		init();

		adminController.chooseEmployee();
		adminController.chooseTest();
		adminController.createNewTask();

		System.assertNotEquals(adminController.notificMap.notificationMap.get('danger'), null);
	}

}