src/objects/Employee__c.object
<CustomObject>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Employee</label>
    <nameField>
        <label>Username</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Pass_History__c.object
<CustomObject>
    <fields>
        <fullName>Employee__c</fullName>
        <label>Employee</label>
        <referenceTo>Employee__c</referenceTo>
        <relationshipLabel>Pass Results</relationshipLabel>
        <relationshipName>Pass_Results</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Result__c</fullName>
        <label>Result</label>
        <precision>4</precision>
        <required>true</required>
        <scale>1</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Test__c</fullName>
        <label>Test</label>
        <referenceTo>Test__c</referenceTo>
        <relationshipLabel>Pass Results</relationshipLabel>
        <relationshipName>Pass_Results</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Pass History</label>
    <nameField>
        <displayFormat>PR-{00000}</displayFormat>
        <label>Pass History #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pass Results</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Subject__c.object
<CustomObject>
    <label>Subject</label>
    <nameField>
        <label>Subject Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subjects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Test__c.object
<CustomObject>
    <fields>
        <fullName>Subject__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subject</label>
        <referenceTo>Subject__c</referenceTo>
        <relationshipLabel>Tests</relationshipLabel>
        <relationshipName>Tests</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Test</label>
    <nameField>
        <label>Test Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/KAStatisticController.cls
public with sharing class KAStatisticController {
	public List<Pass_History__c> recentResults { get; set; }
	public String sortResults { get; set; }
	private Boolean isSort;

	public KAStatisticController() {
		refreshRecentResults();
		sortResults = 'SELECT Employee__r.First_Name__c, Employee__r.Last_Name__c, CreatedDate, Result__c, Test__r.Subject__r.Name, Test__r.Name	FROM Pass_History__c	';
		isSort = true;

	}
	public void refreshRecentResults() {
		recentResults = [
			SELECT Employee__r.First_Name__c, Employee__r.Last_Name__c, CreatedDate, Result__c, Test__r.Subject__r.Name, Test__r.Name
			FROM Pass_History__c
			ORDER BY CreatedDate DESC
			LIMIT 50000
		];
	}

	public void orderByCreatedOn() {
		isSort = isSort ? false : true;

		if (isSort) {
			recentResults = database.query(sortResults + 'ORDER BY CreatedDate DESC  LIMIT 50000');
		}
		else {
			recentResults = database.query(sortResults + 'ORDER BY CreatedDate LIMIT 50000');
		}
	}

	public void orderByName() {
		isSort = isSort ? false : true;

		if (isSort) {
			recentResults = database.query(sortResults + 'ORDER BY Employee__r.First_Name__c LIMIT 50000');
		}
		else {
			recentResults = database.query(sortResults + 'ORDER BY Employee__r.First_Name__c DESC LIMIT 50000');
		}
	}
	public void orderByLastName() {
		isSort = isSort ? false : true;

		if (isSort) {
			recentResults = database.query(sortResults + 'ORDER BY Employee__r.Last_Name__c LIMIT 50000');
		}
		else {
			recentResults = database.query(sortResults + 'ORDER BY Employee__r.Last_Name__c DESC LIMIT 50000');
		}
	}

	public void orderBySubject() {
		isSort = isSort ? false : true;

		if (isSort) {
			recentResults = database.query(sortResults + 'ORDER BY Test__r.Subject__r.Name LIMIT 50000');
		}
		else {
			recentResults = database.query(sortResults + 'ORDER BY Test__r.Subject__r.Name DESC LIMIT 50000');
		}
	}

	public void orderByTestTitle() {
		isSort = isSort ? false : true;

		if (isSort) {
			recentResults = database.query(sortResults + 'ORDER BY Test__r.Name LIMIT 50000');
		}
		else {
			recentResults = database.query(sortResults + 'ORDER BY Test__r.Name DESC LIMIT 50000');
		}
	}

	public void orderByPassResult() {
		isSort = isSort ? false : true;

		if (isSort) {
			recentResults = database.query(sortResults + 'ORDER BY Result__c LIMIT 50000');
		}
		else {
			recentResults = database.query(sortResults + 'ORDER BY Result__c DESC LIMIT 50000');
		}
	}
}