src/objects/Employee__c.object
<CustomObject>
    <fields>
        <fullName>IsAdmin__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsAdmin</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <label>Employee</label>
    <nameField>
        <label>Username</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/KALoginController.cls
public with sharing class KALoginController {

	public String username { get; set; }
	public String password { get; set; }

	private PageReference currentPage;

	public KALoginController() {
		currentPage = ApexPages.currentPage();
	}

	public PageReference onLoad() {
		if (getLoginCookie() != null) {
			Employee__c emploUser = [
				SELECT Name, Password__c, IsAdmin__c
				FROM Employee__c
				WHERE Name =: getLoginCookie().getValue()
				LIMIT 1
			];
			if ( ! emploUser.IsAdmin__c) {
				return new PageReference('/apex/KARegularUserHome');
			}
			else {
				return new PageReference('/apex/KAAdminUserHome');
			}
		}
		else {
			return null;
		}
	}

	public PageReference login() {
		Employee__c emploUser = [
			SELECT Name, Password__c, IsAdmin__c
			FROM Employee__c
			WHERE Name =: username
			LIMIT 1
		];
		if (emploUser != null && emploUser.Password__c == EncodingUtil.convertToHex(Crypto.generateDigest('MD5', Blob.valueOf(password)))) {
			setLoginCookie(username);
			if ( ! emploUser.IsAdmin__c) {
				return new PageReference('/apex/KARegularUserHome');
			}
			else {
				return new PageReference('/apex/KAAdminUserHome');
			}
		}
		return null;
	}

	public PageReference register() {
		return new PageReference('/apex/KARegister');
	}

	public void resetPass() {

	}

	private void setLoginCookie(String username) {
		currentPage.setCookies(
			new Cookie[] {
				new Cookie('KALogin', username, null, 1000, false)
			}
		);
	}

	private Cookie getLoginCookie() {
		return currentPage.getCookies().get('KALogin');
	}

}