src/objects/Subject__c.object
<CustomObject>
    <label>Subject</label>
    <nameField>
        <label>Subject Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subjects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Theme__c.object
<CustomObject>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <referenceTo>Subject__c</referenceTo>
        <relationshipName>Themes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Topic</label>
    <nameField>
        <label>Topic Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Topics</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/KAImportQuestionsCSVControllerTest.cls
@isTest
private class KAImportQuestionsCSVControllerTest {
	private static KAImportQuestionsCSVController csvImportController;
	private static String testCsvFile;
	private static String testInvalidCsvFile;
	private static String testEmptyCsvFile;
	private static Theme__c testTheme;
	private static Subject__c testSubject;

	private static void init(){
		testCsvFile = 'statement; level; riqht1~riqht2; wrong1~wrong2 \n statement; level; riqht1~riqht2; wrong1~wrong2';
		testInvalidCsvFile = 'statement; level; riqht1~riqht2; wrong1;wrong2 \n statement; level; riqht1~riqht2; wrong1~wrong2';
		testEmptyCsvFile = '';
		testSubject = new Subject__c();
		insert testSubject;

		testTheme = new Theme__c(Subject__c = testSubject.Id);
		insert testTheme;

		csvImportController = new KAImportQuestionsCSVController();
		csvImportController.themeId = testTheme.Id;
	}

}